runtime: python
api_version: 1
threadsafe: true
env: flex
entrypoint: gunicorn -b :$PORT main:app
runtime_config:
    python_version: 3
env_variables:
    CLOUD_STORAGE_BUCKET: book-library-12
manual_scaling:
  instances: 1



